#!/usr/bin/env python3
"""Build the static CFP site from decrypted YAML data.

Reads every `data/*.yaml` file (which must already be decrypted by SOPS),
sorts entries by the nearest upcoming deadline, and emits:

  site/cfps.json   – machine-readable dump of all entries
  site/index.html  – human-readable table

The private curation fields (notes/priority/contacts) are intentionally
DROPPED from the public output. They exist only to help you rank/annotate
entries privately; publishing them would defeat the point of encrypting them.
Set PUBLISH_PRIVATE=1 to include them (e.g. for an internal-only build).
"""
from __future__ import annotations

import html
import json
import os
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
OUT_DIR = ROOT / "site"
PRIVATE_FIELDS = {"notes", "priority", "contacts"}
PUBLISH_PRIVATE = os.environ.get("PUBLISH_PRIVATE") == "1"


def load_entries() -> list[dict]:
    entries = []
    for path in sorted(DATA_DIR.glob("*.yaml")) + sorted(DATA_DIR.glob("*.yml")):
        with path.open() as fh:
            data = yaml.safe_load(fh)
        if not isinstance(data, dict):
            print(f"WARN: {path.name} is not a mapping, skipping", file=sys.stderr)
            continue
        data["_source"] = path.name
        entries.append(data)
    return entries


def next_deadline(entry: dict) -> str:
    """Earliest deadline that is still in the future (falls back to earliest)."""
    deadlines = [d for d in (entry.get("deadlines") or {}).values() if d]
    if not deadlines:
        return "9999-12-31"
    today = date.today().isoformat()
    upcoming = sorted(d for d in deadlines if d >= today)
    return upcoming[0] if upcoming else sorted(deadlines)[-1]


def public_view(entry: dict) -> dict:
    if PUBLISH_PRIVATE:
        return entry
    return {k: v for k, v in entry.items() if k not in PRIVATE_FIELDS}


def render_html(entries: list[dict]) -> str:
    rows = []
    for e in entries:
        name = html.escape(str(e.get("name", e.get("id", "?"))))
        cfp_url = html.escape(str(e.get("cfp_url", e.get("website", "#"))))
        topics = html.escape(", ".join(e.get("topics", [])))
        loc = html.escape(str(e.get("location", "—")))
        tier = html.escape(str(e.get("tier", "—")))
        paper_dl = html.escape(str((e.get("deadlines") or {}).get("full_paper", "—")))
        conf = e.get("conference_dates") or {}
        conf_dates = html.escape(f"{conf.get('start', '?')} – {conf.get('end', '?')}")
        rows.append(
            f"    <tr>"
            f"<td><a href='{cfp_url}'>{name}</a></td>"
            f"<td>{tier}</td>"
            f"<td>{topics}</td>"
            f"<td>{loc}</td>"
            f"<td class='dl'>{paper_dl}</td>"
            f"<td>{conf_dates}</td>"
            f"</tr>"
        )
    body = "\n".join(rows)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI Conference Call for Papers</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: system-ui, -apple-system, sans-serif; margin: 2rem auto; max-width: 1000px; padding: 0 1rem; }}
  h1 {{ font-size: 1.6rem; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.95rem; }}
  th, td {{ text-align: left; padding: 0.5rem 0.6rem; border-bottom: 1px solid #8884; }}
  th {{ position: sticky; top: 0; background: Canvas; }}
  td.dl {{ font-variant-numeric: tabular-nums; white-space: nowrap; }}
  a {{ color: inherit; }}
  footer {{ margin-top: 2rem; font-size: 0.85rem; opacity: 0.7; }}
</style>
</head>
<body>
<h1>AI Conference — Call for Papers</h1>
<p>Curated deadlines for reputed global AI conferences, sorted by next deadline.</p>
<table>
  <thead>
    <tr><th>Conference</th><th>Tier</th><th>Topics</th><th>Location</th><th>Paper deadline</th><th>Conference dates</th></tr>
  </thead>
  <tbody>
{body}
  </tbody>
</table>
<footer>Generated by scripts/build.py · data in <code>data/*.yaml</code> · <a href="cfps.json">cfps.json</a></footer>
</body>
</html>
"""


def main() -> int:
    if not DATA_DIR.exists():
        print(f"ERROR: {DATA_DIR} not found", file=sys.stderr)
        return 1
    entries = load_entries()
    entries.sort(key=next_deadline)
    OUT_DIR.mkdir(exist_ok=True)

    public = [public_view(e) for e in entries]
    (OUT_DIR / "cfps.json").write_text(json.dumps(public, indent=2, sort_keys=True))
    (OUT_DIR / "index.html").write_text(render_html(public))
    print(f"Built {len(entries)} CFP entries -> {OUT_DIR}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
